network: "heist_finance_app-network"

connectors:
  - name: "binance-connector"
    image: "heist/binance-connector"
    queue: "binance_trades"

  # - name: "bybit-connector"
  #   image: "heist/bybit-connector"
  #   queue: "bybit_trades"

  # - name: "okx-connector"
  #   image: "heist/okx-connector:latest"
  #   queue: "okx_trades"

preprocessors:
  - name: "binance-preprocessor"
    image: "heist/binance-preprocessor"
    queue: "binance_trades"

  # - name: "bybit-preprocessor"
  #   image: "heist/bybit-preprocessor"
  #   queue: "bybit_trades"

  # - name: "okx-preprocessor"
  #   image: "heist/okx-preprocessor:latest"
  #   queue: "okx_trades"