connectors:
  - name: "binance"
    image: "heist/binance-connector:latest"
  # - name: "bybit"
  #   image: "heist/bybit-connector:latest"
  # - name: "okx"
  #   image: "heist/okx-connector:latest"
  # - name: "mexc"
  #   image: "heist/mexc-connector:latest"
