network: "heist_finance_app-network"

connectors:
  - name: "binance-connector"
    image: "heist/binance-connector:latest"
    exchange: "binance"
    queue: "binance_trades"

  - name: "bybit-connector"
    image: "heist/bybit-connector:latest"
    exchange: "bybit"
    queue: "bybit_trades"

  - name: "okx-connector"
    image: "heist/okx-connector:latest"
    exchange: "okx"
    queue: "okx_trades"

  - name: "coinbase-connector"
    image: "heist/coinbase-connector:latest"
    exchange: "coinbase"
    queue: "coinbase_trades"

preprocessors:
  - name: "binance-preprocessor"
    exchange: "binance"
    image: "heist/binance-preprocessor:latest"
    queue: "binance_trades"

  - name: "bybit-preprocessor"
    exchange: "bybit"
    image: "heist/bybit-preprocessor:latest"
    queue: "bybit_trades"

  - name: "okx-preprocessor"
    exchange: "okx"
    image: "heist/okx-preprocessor:latest"
    queue: "okx_trades"

  - name: "coinbase-preprocessor"
    exchange: "coinbase"
    image: "heist/coinbase-preprocessor:latest"
    queue: "coinbase_trades"