# FROM golang:1.20-alpine

# WORKDIR /app

# # Install Docker client
# RUN apk add --no-cache docker-cli

# # Copy go.mod and go.sum files
# COPY go.mod go.sum ./

# # Download dependencies
# RUN go mod download

# # Copy the source code
# COPY . .

# # Build the application
# RUN go build -o controller cmd/main.go

# # Run the application
# CMD ["./controller"]
